
<html>

<head>
    <meta http-equiv=Content-Type content="text/html; charset=windows-1252">
    <meta charset="utf-8"/>
</head>

<body lang=ES-MX link=blue vlink=purple>
    
    <div class=WordSection1>

    <p class=MsoNormal style='margin-right:4.7pt;text-align:center'><span
    style='font-size:14.0pt;font-family:"Arial",sans-serif'>SECRETAR&Iacute;A DE EDUCACI&Oacute;N P&Uacute;BLICA<br>DIRECCI&Oacute;N GENERAL DEL<br>TECNOL&Oacute;GICO NACIONAL DE M&Eacute;XICO<br>INSTITUTO TECNOL&Oacute;GICO  DE TUXTLA GUTI&Eacute;RREZ</span></p>
   
    
    <br>
    <br>
    
<p class=MsoNormal style='margin-right:4.7pt;text-align:center'><span
    style='font-size:12.0pt;font-family:"Arial",sans-serif'><b>JURAMENTO DE &Eacute;TICA PROFESIONAL</b></span></p>
   <br>
   <br>
   <br>

   <p class=MsoNormal style='margin-right:4.7pt;text-align:justify'><span
    style='font-size:12.0pt;font-family:"Arial",sans-serif'>Como profesionista, dedico mis conocimientos al mejoramiento
    del bienestar humano y brindar a la Instituci&oacute;n la ayuda material e intelectual que este requiera para el mejoramiento
    de la enseñanza.</span></p>
    <br>
    <br>
    <p class=MsoNormal style='margin-right:4.7pt;text-align:justify'><span
    style='font-size:12.0pt;font-family:"Arial",sans-serif'>Me comprometo tambi&eacute;n a dar un rendimiento m&aacute;ximo, a participar
    solo en empresas dignas, a vivir y trabajar de acuerdo con las leyes propias del hombre y el m&aacute;s elevado nivel de conducta profesional
    , a preferir el servicio al aprovechado, el honor y la calidad de la profesi&oacute;n a la ventaja personal y el bien p&uacute;blico a toda
    consideraci&oacute;n.</span></p>
    <br>
    <p class=MsoNormal style='margin-right:4.7pt;text-align:left'><span
    style='font-size:12.0pt;font-family:"Arial",sans-serif'>Con respeto y honradez, hago el presente juramento.</span></p>
    <br>
    <br>
    <br>
    <p class=MsoNormal style='margin-right:4.7pt;text-align:right'><span
    style='font-size:12.0pt;font-family:"Arial",sans-serif'>Tuxtla Guti&eacute;rrez, Chiapas, <?php echo date('d-m-Y'); ?></span></p>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    
    <p class=MsoNormal style='margin-right:4.7pt;text-align:center'><span
    style='font-size:12.0pt;font-family:"Arial",sans-serif'>_____________________________________</span></p>
    
    <p class=MsoNormal style='margin-right:4.7pt;text-align:center'><span
    style='font-size:12.0pt;font-family:"Arial",sans-serif;text-transform: uppercase;'><b><?php echo $data["Tramite"]["nombreComp"]; ?></b></span></p>
    
    <p class=MsoNormal style='margin-right:4.7pt;text-align:center'><span
    style='font-size:12.0pt;font-family:"Arial",sans-serif'><b><?php echo $data["Tramite"]["carrera"]; ?></b></span></p>
</div>

   
   
	
</body>

</html>




