<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Documentos\Module'                        => __DIR__ . '/Module.php',
    'Documentos\Controller\IndexController' => __DIR__ . '/src/Documentos/Controller/IndexController.php',
    'DocumentosTest\Framework\TestCase'        => __DIR__ . '/tests/Documentos/Framework/TestCase.php',
    'DocumentosTest\SampleTest'                => __DIR__ . '/tests/Documentos/SampleTest.php',
);
