<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Division\Module'                        => __DIR__ . '/Module.php',
    'Division\Controller\IndexController' => __DIR__ . '/src/Division/Controller/IndexController.php',
    'DivisionTest\Framework\TestCase'        => __DIR__ . '/tests/Division/Framework/TestCase.php',
    'DivisionTest\SampleTest'                => __DIR__ . '/tests/Division/SampleTest.php',
);
