<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Egresado\Module'                        => __DIR__ . '/Module.php',
    'Egresado\Controller\IndexController' => __DIR__ . '/src/Egresado/Controller/IndexController.php',
    'EgresadoTest\Framework\TestCase'        => __DIR__ . '/tests/Egresado/Framework/TestCase.php',
    'EgresadoTest\SampleTest'                => __DIR__ . '/tests/Egresado/SampleTest.php',
);
