<?php echo $this->doctype(); ?>
<head>
    <title>Sistema de Titulaci&oacute;n</title>
    <?php 
        header('Content-Type: text/html; charset=utf-8');
    ?>
    <link rel="icon" type="image/png" href="<?php echo $this->basepath();?>/img/favicon.png">
     <?php
        $this->headLink()->appendStylesheet($this->basepath("css/reset.css"))
                ->appendStylesheet($this->basepath("css/style.css"))
                ->appendStylesheet($this->basepath("css/grid_12.css"))
                ->appendStylesheet($this->basepath("css/modalDialog.css"));
        echo $this->headLink();
        
        $this->headScript()->appendFile("https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js");
        echo $this->headScript();?>

</head>
<body>
<div id="wrapper">
  <!--==============================header=================================-->
  <div id="header">
<header>
	<h1 style="text-align:center"><a href="index.html"><img src="<?php echo $this->basePath();?>/img/tec.png" alt="" height="90" width="90"></a><span style="font-style: italic;"> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </span>Sistema de apoyo para titulaci&oacute;n</h1>
                <div class="clear"></div>
        <nav class="box-shadow">
            <div>
                <ul class="menu">
                 	<li class="home-page"><a href="<?php echo $this->basePath();?>/"><span></span></a></li>
                    <li><a href="<?php echo $this->basePath();?>/#Egresados">Egresados</a></li>
                    <li><a href="<?php echo $this->basePath();?>/#Division">Divisi&oacute;n</a></li>
                    <li><a href="<?php echo $this->basePath();?>/#Academia">Academia</a></li>
                    <li><a href="<?php echo $this->basePath();?>/#Escolares">Escolares</a></li>
                    <li><a href="<?php echo $this->basePath();?>/application/index/contacto">Contacto</a></li>
                    
                </ul>
                <div class="clear"></div>
            </div>
        </nav>
    </header>
    </div>
    
    <div class="container">
            <?php echo $this->content; ?>
    </div>
    <div id="footer">
    <footer>
		<p>Instituto Tecnol&oacute;gico de Tuxtla Guti&eacute;rrez</p>
        <p>Carretera Panamericana Kil&oacute;metro 1080, Ter&aacute;n, 29050 Tuxtla Guti&eacute;rrez, Chiapas</p>
        <p>Tel. 615 7441</p>
    </footer>
    </div>
</div> <!-- /container -->
</html>