<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Escolares\Module'                        => __DIR__ . '/Module.php',
    'Escolares\Controller\IndexController' => __DIR__ . '/src/Escolares/Controller/IndexController.php',
    'EscolaresTest\Framework\TestCase'        => __DIR__ . '/tests/Escolares/Framework/TestCase.php',
    'EscolaresTest\SampleTest'                => __DIR__ . '/tests/Escolares/SampleTest.php',
);
