<html>

<head>
    <meta http-equiv=Content-Type content="text/html; charset=windows-1252">
    <meta name=Generator content="Microsoft Word 15 (filtered)">
    <meta charset="utf-8"/>
    <link rel="stylesheet" type="text/css" href="estilo.css">

</head>

<body lang=ES-MX link=blue vlink=purple>
    
    <div class=WordSection1>

  
    <p class=MsoNormal style='margin-right:4.7pt;text-align:center'><span
    style='font-size:9.0pt;font-family:"Arial",sans-serif'>INSTITUTO TECNOL&Oacute;GICO  DE TUXTLA GUTI&Eacute;RREZ <br> DEPARTAMENTO DE SERVICIOS ESCOLARES <br> OFICINAS DE SERVICIOS ESTUDIANTILES </span></p>
     <p class=MsoNormal style='margin-right:4.7pt;text-align:center'><span
    style='font-size:9.0pt;font-family:"Arial",sans-serif'>REQUISITOS PARA TR&Aacute;MITE DE OBTENCI&Oacute;N DE T&Iacute;TULO Y C&Eacute;DULA PROFESIONAL UNA VEZ OBTENIDA LA OPCI&Oacute;N SELECCIONADA</span></p>
   
   <p class=MsoNormal style='margin-right:4.7pt;text-align:justify'><span
    style='font-size:15.0pt;font-family:"Arial",sans-serif'><i>Todas las copias deben ser tamaño <b>carta, legibles, completas </b> y  con <b> calidad fotográfica en blanco y negro.</b></i></span></p>
    
    <ul style="text-align:justify">
        <li>FORMATO DGP/DR-01 (llenar a mano <b>con letra de molde, lapicero Bic tinta negra punto mediano, en may&uacute;sculas y min&uacute;sculas,</b> 2 tantos originales).</li>
        <li>ACTA DE NACIMIENTO Actualizada de 5 años a la fecha, Original y dos copias (<b>sello legible y completo</b>).</li>
        <li>C.U.R.P. (dos copias en ampliaci&oacute;n a media carta, ambos lados).</li>
        <li>CERTIFICADO DE BACHILLERATO (Original y una copia).</li>
        <li>CERTIFICADO DE LICENCIATURA(Original y dos copias).</li>
        <li>CONSTANCIA DE LIBERACI&Oacute;N DE SERVICIO SOCIAL(Original y una copia).</li>
        <li>CONSTANCIA DE LIBERACI&Oacute;N DE PRACTICAS PROFESIONALES(Original y una copias; para planes de estudios <b>73-80 y 90</b>).</li>
        <li>CONSTANCIA DE ACREDITACI&Oacute;N DE IDIOMA INGL&Eacute;S(Expedida por Servicios Escolares, original y una copia) Y UNA COPIA DEL ACTA DE APROBACI&Oacute;N(Expedida por la divisi&oacute;n de Estudios Profesionales)</li>
        <li>4 FOTOGRAF&Iacute;AS TAMAÑO CREDENCIAL OVALADAS Y 6 FOTOGRAF&Iacute;S TAMAÑO INFANTIL RECIENTES, DE FRENTE, CENTRADAS, CON TRAJE OSCURO, RETOCADAS EN <b>PAPEL DELGADO, CON ADHESIVO Y SIN BRILLO, en B/N</b> con nombre al reverso a l&aacute;piz (<b>HOMBRES:</b> sin barba, <b>MUJERES:</b> maquillaje discreto, aretes pequeños, cabello levantado o suelto, siempre y cuando no interfiera en el rostro).</li>
        <li>FORMATO PARA RECABAR SELLOS DE NO ADEUDO DE MATERIAL, CORRESPONDIENTES A LA CARRERA Y ADICIONAL BIBLIOTECA.</li>
        <li>4 FOLFERS TAMAÑO OFICIO COLORES CREMA Y DOS SOBRES PAPEL MALINA T/OFICIO, (NO SUCIOS, NI DETERIORADOS).</li>

    </ul>
  <p><b><u>ANEXAR OFICIO SEG&Uacute;N OPCI&Oacute;N</u></b></p>

  <ul style="text-align:justify">
      <li>OFICIO DE AUTORIZACI&Oacute;N DE IMPRESI&Oacute;N DEL TRABAJO PROFESIONAL, PARA LAS OPCIONES <b>I,II,II,IV,V,VII,X y T.I.</b>(&uacute;nicamente copia).</li>
      <li>OPCION VI:
        <li><b>EXAMEN POR &Aacute;REAS:</b> OFICIO DE CONCLUCI&Oacute;N DE ASESOR&Iacute;A(copia).</li>
        <li><b>EXAMEN CENEVAL:</b> TESTIMONIO DE DESEMPEÑO DEL CENEVAL (copia). Y COPIA DE OFICIO DE CONCLUSI&Oacute;N DE ASESOR&Iacute;S.</li></li>
        <li>OPCI&Oacute;N IX-OFICIO DE AUTORIZACI&Oacute;N PARA TITULARSE Y CONSTNCIA DEL 40% DE CR&Eacute;DITOS APROBADOS DE LA MAESTRIA (una copia de c/documento).</li>
  </ul>
   <p class=MsoNormal style='margin-right:4.7pt;text-align:center'><span
    style='font-size:15.0pt;font-family:"Arial",sans-serif'><i><b>Nota: No Se recibir&aacute; expediente en caso de estar incompleto</b></i></span></p>

    <p style="text-align:center">Horario de atenci&oacute;n: de lunes a viernes de <b><u>9:00 a 12:00</u></b> hrs. (<b>con previa cita</b>)<br>
    TELEFONOS:  6150380, 6150461, EXT. 415</p>
    

   
   
	
</body>

</html>





