<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Academia\Module'                        => __DIR__ . '/Module.php',
    'Academia\Controller\IndexController' => __DIR__ . '/src/Academia/Controller/IndexController.php',
    'AcademiaTest\Framework\TestCase'        => __DIR__ . '/tests/Academia/Framework/TestCase.php',
    'AcademiaTest\SampleTest'                => __DIR__ . '/tests/Academia/SampleTest.php',
);
