<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Informacion\Module'                        => __DIR__ . '/Module.php',
    'Informacion\Controller\IndexController' => __DIR__ . '/src/Informacion/Controller/IndexController.php',
);
